Графика всех страниц
htmlacademy-htmlcss/1292461-sedona-30 pull request #4
Opened 2021-02-01 15:21 UTC by djingreen

2021-02-02 20:12 UTC, raccoonroman requested changes
* иконки должны быть в svg-формате: https://prnt.sc/y22ws7, https://prnt.sc/y22xrc
* https://prnt.sc/y22zvj это всё одна свг, нет смысла извлекать части по отдельности
* https://github.com/htmlacademy-htmlcss/1292461-sedona-30/blob/ff28cebf035296f366f5452aea29f0c3e14dc187/img/logo/logo_htmlacademy.png не понимаю, почему лого академии в таком цвете. Его нужно извлечь в svg, а цвет при взаимодействии будет меняться с помощью стилей.

2021-02-02 20:12 UTC, raccoonroman commented on catalog.html
>    </head>
почему нет остальных версий фавиконок?

2021-02-03 18:50 UTC, djingreen commented on catalog.html
>    </head>
1. иконки исправил на svg формат.
2. Объединил в одну большую иконку
3. лого академии тоже в svg
4. добавил остальные версии иконок.

2021-02-03 19:31 UTC, raccoonroman approved these changes
Fire! 👍

2021-02-03 19:31 UTC, merged